package main

import (
	"encoding/base64"
)

func base64decodeSql(input string) string {
    content, err := base64.StdEncoding.DecodeString(input)
    if err != nil {
        return input
    }
    return string(content)
}



const QueryInsertAttachment = "InsertAttachment"

const QueryInsertRecord = "InsertRecord"

const QueryInsertRecordParent = "InsertRecordParent"

const QuerySelectAllPayloads = "SelectAllPayloads"

const QuerySelectAllRecords = "SelectAllRecords"

const QuerySelectAnswerids = "SelectAnswerids"

const QuerySelectAnswers = "SelectAnswers"

const QuerySelectAttachment = "SelectAttachment"

const QuerySelectAttachments = "SelectAttachments"

const QuerySelectDomainMx = "SelectDomainMx"

const QuerySelectDomains = "SelectDomains"

const QuerySelectFirstRecord = "SelectFirstRecord"

const QuerySelectIntopic = "SelectIntopic"

const QuerySelectRecord = "SelectRecord"

const QuerySelectRecordDomain = "SelectRecordDomain"

const QuerySelectRecordsSince = "SelectRecordsSince"

const QuerySelectRecordsTopicSince = "SelectRecordsTopicSince"

const QuerySelectTopics = "SelectTopics"

const QueryTruncateAttachments = "TruncateAttachments"


func RegisterQueries(store Store) {
	
	store.Register(QueryInsertAttachment, base64decodeSql(`LS0gaW5zZXJ0IGF0dGFjaG1lbnQKCklOU0VSVCBJTlRPIHt7LkF0dGFjaG1lbnRzfX0KICAgIChyZWNvcmRfaWQsIGNvbnRlbnRfdHlwZSwgZmlsZV9uYW1lKQpWQUxVRVMgCiAgICAoJDEsICQyLCAkMyk=`))
	
	store.Register(QueryInsertRecord, base64decodeSql(`LS0gaW5zZXJ0IHJlY29yZAoKSU5TRVJUIElOVE8ge3suUmVjb3Jkc319IAooCiAgICBzZW5kZXIsIAogICAgcmVjaXBpZW50LCAKICAgIHRvcGljLCAKICAgIGRvbWFpbiwgCiAgICBoZWFkZXJfZGF0ZSwgCiAgICBoZWFkZXJfc3ViamVjdCwgCiAgICBib2R5LCAKICAgIHBheWxvYWQKKQpWQUxVRVMgKCQxLCAkMiwgJDMsICQ0LCAkNSwgJDYsICQ3LCAkOCkKUkVUVVJOSU5HIGlk`))
	
	store.Register(QueryInsertRecordParent, base64decodeSql(`LS0gaW5zZXJ0IHJlY29yZAoKSU5TRVJUIElOVE8ge3suUmVjb3Jkc319IAooCiAgICBzZW5kZXIsIAogICAgcmVjaXBpZW50LCAKICAgIHRvcGljLCAKICAgIGRvbWFpbiwgCiAgICBoZWFkZXJfZGF0ZSwgCiAgICBoZWFkZXJfc3ViamVjdCwgCiAgICBib2R5LCAKICAgIHBheWxvYWQsIAogICAgcGFyZW50CikKVkFMVUVTICgkMSwgJDIsICQzLCAkNCwgJDUsICQ2LCAkNywgJDgsICQ5KQpSRVRVUk5JTkcgaWQ=`))
	
	store.Register(QuerySelectAllPayloads, base64decodeSql(`U0VMRUNUICAKICAgIGlkLCBzZW5kZXIsIHRvcGljLCBwYXlsb2FkCkZST00ge3suUmVjb3Jkc319`))
	
	store.Register(QuerySelectAllRecords, base64decodeSql(`U0VMRUNUICAKICAgIGlkLCB0cywgc2VuZGVyLCB0b3BpYywgaGVhZGVyX3N1YmplY3QsIGJvZHkgCkZST00ge3suUmVjb3Jkc319Ow==`))
	
	store.Register(QuerySelectAnswerids, base64decodeSql(`LS0gYW5zd2VyIGlkcwpTRUxFQ1QgaWQsIHNlbmRlcgpGUk9NIHt7LlJlY29yZHN9fQpXSEVSRSBwYXJlbnQgPSAkMQpPUkRFUiBCWSB0cyBBU0M=`))
	
	store.Register(QuerySelectAnswers, base64decodeSql(`LS0gYW5zd2VycwpTRUxFQ1QgIAogICAgaWQsIHRzLCBzZW5kZXIsIHRvcGljLCBoZWFkZXJfc3ViamVjdCwgYm9keSwgcGFyZW50IApGUk9NIHt7LlJlY29yZHN9fSAKV0hFUkUgcGFyZW50ID0gJDEKT1JERVIgQlkgdHMgQVND`))
	
	store.Register(QuerySelectAttachment, base64decodeSql(`LS0gYXR0YWNobWVudCAoc2luZ2xlKQpTRUxFQ1QgY29udGVudF90eXBlLCBmaWxlX25hbWUKRlJPTSB7ey5BdHRhY2htZW50c319CldIRVJFIAogICAgcmVjb3JkX2lkID0gJDEgCiAgICBBTkQgZmlsZV9uYW1lID0gJDI=`))
	
	store.Register(QuerySelectAttachments, base64decodeSql(`U0VMRUNUIHJlY29yZF9pZCwgY29udGVudF90eXBlLCBmaWxlX25hbWUKRlJPTSB7ey5BdHRhY2htZW50c319CldIRVJFIHJlY29yZF9pZCA9ICQx`))
	
	store.Register(QuerySelectDomainMx, base64decodeSql(`U0VMRUNUIAogICAgaWQKRlJPTSB7ey5Eb21haW5zfX0KV0hFUkUgbXhfbmFtZSA9ICQx`))
	
	store.Register(QuerySelectDomains, base64decodeSql(`U0VMRUNUIAogICAgaHR0cF9uYW1lLCBteF9uYW1lCkZST00ge3suRG9tYWluc319`))
	
	store.Register(QuerySelectFirstRecord, base64decodeSql(`U0VMRUNUICAKICAgIGlkLCB0cywgc2VuZGVyLCBoZWFkZXJfc3ViamVjdCAKRlJPTSB7ey5SZWNvcmRzfX0gCldIRVJFCiAgICBkb21haW4gPSAkMQogICAgQU5EIHRvcGljID0gJDIKT1JERVIgQlkgdHMgIEFTQwpMSU1JVCAx`))
	
	store.Register(QuerySelectIntopic, base64decodeSql(`U0VMRUNUIGlkLCB0cywgc2VuZGVyLCBoZWFkZXJfc3ViamVjdApGUk9NIHt7LlJlY29yZHN9fSAgCldIRVJFIAogICAgZG9tYWluID0gJDEKICAgIEFORCB0b3BpYyA9ICQyIAogICAgQU5EIHBhcmVudCBJUyBOVUxMIApPUkRFUiBCWSB0cyBERVND`))
	
	store.Register(QuerySelectRecord, base64decodeSql(`U0VMRUNUICAKICAgIGlkLCB0cywgc2VuZGVyLCB0b3BpYywgaGVhZGVyX3N1YmplY3QsIGJvZHksIHBhcmVudCAKRlJPTSB7ey5SZWNvcmRzfX0gCldIRVJFIAogICAgaWQgPSAkMQ==`))
	
	store.Register(QuerySelectRecordDomain, base64decodeSql(`U0VMRUNUICAKICAgIGlkLCB0cywgc2VuZGVyLCB0b3BpYywgaGVhZGVyX3N1YmplY3QsIGJvZHksIHBhcmVudCAKRlJPTSB7ey5SZWNvcmRzfX0gCldIRVJFIAogICAgZG9tYWluID0gJDEKICAgIEFORCBpZCA9ICQy`))
	
	store.Register(QuerySelectRecordsSince, base64decodeSql(`U0VMRUNUICAKICAgIGlkLCB0cywgc2VuZGVyLCB0b3BpYywgaGVhZGVyX3N1YmplY3QsIGJvZHkgCkZST00ge3suUmVjb3Jkc319IApXSEVSRSAKICAgIGRvbWFpbiA9ICQxCiAgICBBTkQgdHMgPj0gJDI6OmRhdGU=`))
	
	store.Register(QuerySelectRecordsTopicSince, base64decodeSql(`U0VMRUNUICAKICAgIGlkLCB0cywgc2VuZGVyLCB0b3BpYywgaGVhZGVyX3N1YmplY3QsIGJvZHkgCkZST00ge3suUmVjb3Jkc319IApXSEVSRSAKICAgIGRvbWFpbiA9ICQxCiAgICBBTkQgdG9waWMgPSAkMgogICAgQU5EIHRzID49ICQzOjpkYXRlCiAgICBBTkQgcGFyZW50IElTIE5VTEwg`))
	
	store.Register(QuerySelectTopics, base64decodeSql(`U0VMRUNUIAogICAgRElTVElOQ1QodG9waWMpIAogICAgdG9waWMsIAogICAgY291bnQoaWQpIGFzIGNvdW50LCAKICAgIG1heCh0cykgYXMgbXRzCkZST00ge3suUmVjb3Jkc319IApXSEVSRQogICAgZG9tYWluID0gJDEKICAgIEFORCBzdHJwb3ModG9waWMsICdfJykgPD4gMQpHUk9VUCBCWSB0b3BpYwpPUkRFUiBCWSB0b3BpYyBBU0M=`))
	
	store.Register(QueryTruncateAttachments, base64decodeSql(`LS0gdHJ1bmNhdGUgYXR0YWNobWVudHMgdGFibGUgKGdlbmVyYWxseSBiZWZvcmUgcmVnZW5lcmF0aW5nIHdpdGggc2VkZCBvcHRpb24pClRSVU5DQVRFIFRBQkxFIHt7LkF0dGFjaG1lbnRzfX07`))
	
}